version: '3.9'

services:
  postgres:
    container_name: postgres_apigo
    image: postgres:14.5
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - apigo:/var/lib/postgresql/data
    networks:
      - apigo_net
  
  apigo:
    container_name: api_go_dev
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - 8080:8080
    networks:
      - apigo_net
      
networks:
  apigo_net:
    driver: bridge

volumes:
  apigo:    
