definitions:
  dto.UpdateUserDto:
    properties:
      cep:
        type: string
      email:
        type: string
      name:
        maxLength: 30
        minLength: 3
        type: string
    required:
    - cep
    type: object
  httperr.Fields:
    properties:
      field:
        type: string
      message:
        type: string
      value: {}
    type: object
  httperr.RestErr:
    properties:
      code:
        type: integer
      err:
        type: string
      fields:
        items:
          $ref: '#/definitions/httperr.Fields'
        type: array
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /user:
    patch:
      consumes:
      - application/json
      description: Endpoint for update user
      parameters:
      - description: Update user dto
        in: body
        name: body
        schema:
          $ref: '#/definitions/dto.UpdateUserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperr.RestErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httperr.RestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.RestErr'
      security:
      - ApiKeyAuth: []
      summary: Update user
      tags:
      - user
swagger: "2.0"
